/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KategorieParentRouteImport } from './routes/kategorie.$parent'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as KategorieParentChildRouteImport } from './routes/kategorie.$parent.$child'
import { Route as ApiPublicTrackClickRouteImport } from './routes/api/public/track-click'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as ApiPublicHooksKeepaSyncRouteImport } from './routes/api/public/hooks/keepa-sync'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorieParentRoute = KategorieParentRouteImport.update({
  id: '/kategorie/$parent',
  path: '/kategorie/$parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const KategorieParentChildRoute = KategorieParentChildRouteImport.update({
  id: '/$child',
  path: '/$child',
  getParentRoute: () => KategorieParentRoute,
} as any)
const ApiPublicTrackClickRoute = ApiPublicTrackClickRouteImport.update({
  id: '/api/public/track-click',
  path: '/api/public/track-click',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksKeepaSyncRoute = ApiPublicHooksKeepaSyncRouteImport.update({
  id: '/api/public/hooks/keepa-sync',
  path: '/api/public/hooks/keepa-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/kategorie/$parent': typeof KategorieParentRouteWithChildren
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/api/public/track-click': typeof ApiPublicTrackClickRoute
  '/kategorie/$parent/$child': typeof KategorieParentChildRoute
  '/api/public/hooks/keepa-sync': typeof ApiPublicHooksKeepaSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/kategorie/$parent': typeof KategorieParentRouteWithChildren
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/api/public/track-click': typeof ApiPublicTrackClickRoute
  '/kategorie/$parent/$child': typeof KategorieParentChildRoute
  '/api/public/hooks/keepa-sync': typeof ApiPublicHooksKeepaSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/kategorie/$parent': typeof KategorieParentRouteWithChildren
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/api/public/track-click': typeof ApiPublicTrackClickRoute
  '/kategorie/$parent/$child': typeof KategorieParentChildRoute
  '/api/public/hooks/keepa-sync': typeof ApiPublicHooksKeepaSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/watchlist'
    | '/kategorie/$parent'
    | '/admin/categories'
    | '/api/public/track-click'
    | '/kategorie/$parent/$child'
    | '/api/public/hooks/keepa-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/watchlist'
    | '/kategorie/$parent'
    | '/admin/categories'
    | '/api/public/track-click'
    | '/kategorie/$parent/$child'
    | '/api/public/hooks/keepa-sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/watchlist'
    | '/kategorie/$parent'
    | '/_authenticated/admin/categories'
    | '/api/public/track-click'
    | '/kategorie/$parent/$child'
    | '/api/public/hooks/keepa-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KategorieParentRoute: typeof KategorieParentRouteWithChildren
  ApiPublicTrackClickRoute: typeof ApiPublicTrackClickRoute
  ApiPublicHooksKeepaSyncRoute: typeof ApiPublicHooksKeepaSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorie/$parent': {
      id: '/kategorie/$parent'
      path: '/kategorie/$parent'
      fullPath: '/kategorie/$parent'
      preLoaderRoute: typeof KategorieParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/kategorie/$parent/$child': {
      id: '/kategorie/$parent/$child'
      path: '/$child'
      fullPath: '/kategorie/$parent/$child'
      preLoaderRoute: typeof KategorieParentChildRouteImport
      parentRoute: typeof KategorieParentRoute
    }
    '/api/public/track-click': {
      id: '/api/public/track-click'
      path: '/api/public/track-click'
      fullPath: '/api/public/track-click'
      preLoaderRoute: typeof ApiPublicTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/keepa-sync': {
      id: '/api/public/hooks/keepa-sync'
      path: '/api/public/hooks/keepa-sync'
      fullPath: '/api/public/hooks/keepa-sync'
      preLoaderRoute: typeof ApiPublicHooksKeepaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface KategorieParentRouteChildren {
  KategorieParentChildRoute: typeof KategorieParentChildRoute
}

const KategorieParentRouteChildren: KategorieParentRouteChildren = {
  KategorieParentChildRoute: KategorieParentChildRoute,
}

const KategorieParentRouteWithChildren = KategorieParentRoute._addFileChildren(
  KategorieParentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KategorieParentRoute: KategorieParentRouteWithChildren,
  ApiPublicTrackClickRoute: ApiPublicTrackClickRoute,
  ApiPublicHooksKeepaSyncRoute: ApiPublicHooksKeepaSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
