/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ParentRouteImport } from './routes/$parent'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentIndexRouteImport } from './routes/$parent.index'
import { Route as KategorieParentRouteImport } from './routes/kategorie.$parent'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as ParentChildRouteImport } from './routes/$parent.$child'
import { Route as KategorieParentIndexRouteImport } from './routes/kategorie.$parent.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as KategorieParentChildRouteImport } from './routes/kategorie.$parent.$child'
import { Route as ApiPublicTrackClickRouteImport } from './routes/api/public/track-click'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin.subscribers'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminEmailTemplatesRouteImport } from './routes/_authenticated/admin.email-templates'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksPriceAlertCheckRouteImport } from './routes/api/public/hooks/price-alert-check'
import { Route as ApiPublicHooksKeepaSyncRouteImport } from './routes/api/public/hooks/keepa-sync'
import { Route as ApiPublicHooksKeepaRefreshRouteImport } from './routes/api/public/hooks/keepa-refresh'
import { Route as ApiPublicHooksKeepaBackfillCategoriesRouteImport } from './routes/api/public/hooks/keepa-backfill-categories'
import { Route as ApiPublicHooksAdminDailyDigestRouteImport } from './routes/api/public/hooks/admin-daily-digest'
import { Route as ApiPublicEmailWatchSubscribeRouteImport } from './routes/api/public/email/watch-subscribe'
import { Route as ApiPublicEmailConfirmRouteImport } from './routes/api/public/email/confirm'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/$parent',
  path: '/$parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const KategorieParentRoute = KategorieParentRouteImport.update({
  id: '/kategorie/$parent',
  path: '/kategorie/$parent',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ParentChildRoute = ParentChildRouteImport.update({
  id: '/$child',
  path: '/$child',
  getParentRoute: () => ParentRoute,
} as any)
const KategorieParentIndexRoute = KategorieParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KategorieParentRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorieParentChildRoute = KategorieParentChildRouteImport.update({
  id: '/$child',
  path: '/$child',
  getParentRoute: () => KategorieParentRoute,
} as any)
const ApiPublicTrackClickRoute = ApiPublicTrackClickRouteImport.update({
  id: '/api/public/track-click',
  path: '/api/public/track-click',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/admin/subscribers',
    path: '/admin/subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEmailTemplatesRoute =
  AuthenticatedAdminEmailTemplatesRouteImport.update({
    id: '/admin/email-templates',
    path: '/admin/email-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPriceAlertCheckRoute =
  ApiPublicHooksPriceAlertCheckRouteImport.update({
    id: '/api/public/hooks/price-alert-check',
    path: '/api/public/hooks/price-alert-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKeepaSyncRoute = ApiPublicHooksKeepaSyncRouteImport.update({
  id: '/api/public/hooks/keepa-sync',
  path: '/api/public/hooks/keepa-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksKeepaRefreshRoute =
  ApiPublicHooksKeepaRefreshRouteImport.update({
    id: '/api/public/hooks/keepa-refresh',
    path: '/api/public/hooks/keepa-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKeepaBackfillCategoriesRoute =
  ApiPublicHooksKeepaBackfillCategoriesRouteImport.update({
    id: '/api/public/hooks/keepa-backfill-categories',
    path: '/api/public/hooks/keepa-backfill-categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAdminDailyDigestRoute =
  ApiPublicHooksAdminDailyDigestRouteImport.update({
    id: '/api/public/hooks/admin-daily-digest',
    path: '/api/public/hooks/admin-daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailWatchSubscribeRoute =
  ApiPublicEmailWatchSubscribeRouteImport.update({
    id: '/api/public/email/watch-subscribe',
    path: '/api/public/email/watch-subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailConfirmRoute = ApiPublicEmailConfirmRouteImport.update({
  id: '/api/public/email/confirm',
  path: '/api/public/email/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$parent': typeof ParentRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$parent/$child': typeof ParentChildRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/kategorie/$parent': typeof KategorieParentRouteWithChildren
  '/$parent/': typeof ParentIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/track-click': typeof ApiPublicTrackClickRoute
  '/kategorie/$parent/$child': typeof KategorieParentChildRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/kategorie/$parent/': typeof KategorieParentIndexRoute
  '/api/public/email/confirm': typeof ApiPublicEmailConfirmRoute
  '/api/public/email/watch-subscribe': typeof ApiPublicEmailWatchSubscribeRoute
  '/api/public/hooks/admin-daily-digest': typeof ApiPublicHooksAdminDailyDigestRoute
  '/api/public/hooks/keepa-backfill-categories': typeof ApiPublicHooksKeepaBackfillCategoriesRoute
  '/api/public/hooks/keepa-refresh': typeof ApiPublicHooksKeepaRefreshRoute
  '/api/public/hooks/keepa-sync': typeof ApiPublicHooksKeepaSyncRoute
  '/api/public/hooks/price-alert-check': typeof ApiPublicHooksPriceAlertCheckRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$parent/$child': typeof ParentChildRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/$parent': typeof ParentIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/track-click': typeof ApiPublicTrackClickRoute
  '/kategorie/$parent/$child': typeof KategorieParentChildRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/kategorie/$parent': typeof KategorieParentIndexRoute
  '/api/public/email/confirm': typeof ApiPublicEmailConfirmRoute
  '/api/public/email/watch-subscribe': typeof ApiPublicEmailWatchSubscribeRoute
  '/api/public/hooks/admin-daily-digest': typeof ApiPublicHooksAdminDailyDigestRoute
  '/api/public/hooks/keepa-backfill-categories': typeof ApiPublicHooksKeepaBackfillCategoriesRoute
  '/api/public/hooks/keepa-refresh': typeof ApiPublicHooksKeepaRefreshRoute
  '/api/public/hooks/keepa-sync': typeof ApiPublicHooksKeepaSyncRoute
  '/api/public/hooks/price-alert-check': typeof ApiPublicHooksPriceAlertCheckRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$parent': typeof ParentRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$parent/$child': typeof ParentChildRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/kategorie/$parent': typeof KategorieParentRouteWithChildren
  '/$parent/': typeof ParentIndexRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/track-click': typeof ApiPublicTrackClickRoute
  '/kategorie/$parent/$child': typeof KategorieParentChildRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/kategorie/$parent/': typeof KategorieParentIndexRoute
  '/api/public/email/confirm': typeof ApiPublicEmailConfirmRoute
  '/api/public/email/watch-subscribe': typeof ApiPublicEmailWatchSubscribeRoute
  '/api/public/hooks/admin-daily-digest': typeof ApiPublicHooksAdminDailyDigestRoute
  '/api/public/hooks/keepa-backfill-categories': typeof ApiPublicHooksKeepaBackfillCategoriesRoute
  '/api/public/hooks/keepa-refresh': typeof ApiPublicHooksKeepaRefreshRoute
  '/api/public/hooks/keepa-sync': typeof ApiPublicHooksKeepaSyncRoute
  '/api/public/hooks/price-alert-check': typeof ApiPublicHooksPriceAlertCheckRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$parent'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/$parent/$child'
    | '/watchlist'
    | '/email/unsubscribe'
    | '/kategorie/$parent'
    | '/$parent/'
    | '/admin/categories'
    | '/admin/email-templates'
    | '/admin/pages'
    | '/admin/subscribers'
    | '/api/public/track-click'
    | '/kategorie/$parent/$child'
    | '/lovable/email/suppression'
    | '/kategorie/$parent/'
    | '/api/public/email/confirm'
    | '/api/public/email/watch-subscribe'
    | '/api/public/hooks/admin-daily-digest'
    | '/api/public/hooks/keepa-backfill-categories'
    | '/api/public/hooks/keepa-refresh'
    | '/api/public/hooks/keepa-sync'
    | '/api/public/hooks/price-alert-check'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/$parent/$child'
    | '/watchlist'
    | '/email/unsubscribe'
    | '/$parent'
    | '/admin/categories'
    | '/admin/email-templates'
    | '/admin/pages'
    | '/admin/subscribers'
    | '/api/public/track-click'
    | '/kategorie/$parent/$child'
    | '/lovable/email/suppression'
    | '/kategorie/$parent'
    | '/api/public/email/confirm'
    | '/api/public/email/watch-subscribe'
    | '/api/public/hooks/admin-daily-digest'
    | '/api/public/hooks/keepa-backfill-categories'
    | '/api/public/hooks/keepa-refresh'
    | '/api/public/hooks/keepa-sync'
    | '/api/public/hooks/price-alert-check'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$parent'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/$parent/$child'
    | '/_authenticated/watchlist'
    | '/email/unsubscribe'
    | '/kategorie/$parent'
    | '/$parent/'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/email-templates'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/subscribers'
    | '/api/public/track-click'
    | '/kategorie/$parent/$child'
    | '/lovable/email/suppression'
    | '/kategorie/$parent/'
    | '/api/public/email/confirm'
    | '/api/public/email/watch-subscribe'
    | '/api/public/hooks/admin-daily-digest'
    | '/api/public/hooks/keepa-backfill-categories'
    | '/api/public/hooks/keepa-refresh'
    | '/api/public/hooks/keepa-sync'
    | '/api/public/hooks/price-alert-check'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  KategorieParentRoute: typeof KategorieParentRouteWithChildren
  ApiPublicTrackClickRoute: typeof ApiPublicTrackClickRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicEmailConfirmRoute: typeof ApiPublicEmailConfirmRoute
  ApiPublicEmailWatchSubscribeRoute: typeof ApiPublicEmailWatchSubscribeRoute
  ApiPublicHooksAdminDailyDigestRoute: typeof ApiPublicHooksAdminDailyDigestRoute
  ApiPublicHooksKeepaBackfillCategoriesRoute: typeof ApiPublicHooksKeepaBackfillCategoriesRoute
  ApiPublicHooksKeepaRefreshRoute: typeof ApiPublicHooksKeepaRefreshRoute
  ApiPublicHooksKeepaSyncRoute: typeof ApiPublicHooksKeepaSyncRoute
  ApiPublicHooksPriceAlertCheckRoute: typeof ApiPublicHooksPriceAlertCheckRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$parent': {
      id: '/$parent'
      path: '/$parent'
      fullPath: '/$parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$parent/': {
      id: '/$parent/'
      path: '/'
      fullPath: '/$parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/kategorie/$parent': {
      id: '/kategorie/$parent'
      path: '/kategorie/$parent'
      fullPath: '/kategorie/$parent'
      preLoaderRoute: typeof KategorieParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$parent/$child': {
      id: '/$parent/$child'
      path: '/$child'
      fullPath: '/$parent/$child'
      preLoaderRoute: typeof ParentChildRouteImport
      parentRoute: typeof ParentRoute
    }
    '/kategorie/$parent/': {
      id: '/kategorie/$parent/'
      path: '/'
      fullPath: '/kategorie/$parent/'
      preLoaderRoute: typeof KategorieParentIndexRouteImport
      parentRoute: typeof KategorieParentRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorie/$parent/$child': {
      id: '/kategorie/$parent/$child'
      path: '/$child'
      fullPath: '/kategorie/$parent/$child'
      preLoaderRoute: typeof KategorieParentChildRouteImport
      parentRoute: typeof KategorieParentRoute
    }
    '/api/public/track-click': {
      id: '/api/public/track-click'
      path: '/api/public/track-click'
      fullPath: '/api/public/track-click'
      preLoaderRoute: typeof ApiPublicTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-templates': {
      id: '/_authenticated/admin/email-templates'
      path: '/admin/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AuthenticatedAdminEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/price-alert-check': {
      id: '/api/public/hooks/price-alert-check'
      path: '/api/public/hooks/price-alert-check'
      fullPath: '/api/public/hooks/price-alert-check'
      preLoaderRoute: typeof ApiPublicHooksPriceAlertCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/keepa-sync': {
      id: '/api/public/hooks/keepa-sync'
      path: '/api/public/hooks/keepa-sync'
      fullPath: '/api/public/hooks/keepa-sync'
      preLoaderRoute: typeof ApiPublicHooksKeepaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/keepa-refresh': {
      id: '/api/public/hooks/keepa-refresh'
      path: '/api/public/hooks/keepa-refresh'
      fullPath: '/api/public/hooks/keepa-refresh'
      preLoaderRoute: typeof ApiPublicHooksKeepaRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/keepa-backfill-categories': {
      id: '/api/public/hooks/keepa-backfill-categories'
      path: '/api/public/hooks/keepa-backfill-categories'
      fullPath: '/api/public/hooks/keepa-backfill-categories'
      preLoaderRoute: typeof ApiPublicHooksKeepaBackfillCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/admin-daily-digest': {
      id: '/api/public/hooks/admin-daily-digest'
      path: '/api/public/hooks/admin-daily-digest'
      fullPath: '/api/public/hooks/admin-daily-digest'
      preLoaderRoute: typeof ApiPublicHooksAdminDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/watch-subscribe': {
      id: '/api/public/email/watch-subscribe'
      path: '/api/public/email/watch-subscribe'
      fullPath: '/api/public/email/watch-subscribe'
      preLoaderRoute: typeof ApiPublicEmailWatchSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/confirm': {
      id: '/api/public/email/confirm'
      path: '/api/public/email/confirm'
      fullPath: '/api/public/email/confirm'
      preLoaderRoute: typeof ApiPublicEmailConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminEmailTemplatesRoute: typeof AuthenticatedAdminEmailTemplatesRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminEmailTemplatesRoute: AuthenticatedAdminEmailTemplatesRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ParentRouteChildren {
  ParentChildRoute: typeof ParentChildRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentChildRoute: ParentChildRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface KategorieParentRouteChildren {
  KategorieParentChildRoute: typeof KategorieParentChildRoute
  KategorieParentIndexRoute: typeof KategorieParentIndexRoute
}

const KategorieParentRouteChildren: KategorieParentRouteChildren = {
  KategorieParentChildRoute: KategorieParentChildRoute,
  KategorieParentIndexRoute: KategorieParentIndexRoute,
}

const KategorieParentRouteWithChildren = KategorieParentRoute._addFileChildren(
  KategorieParentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  KategorieParentRoute: KategorieParentRouteWithChildren,
  ApiPublicTrackClickRoute: ApiPublicTrackClickRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicEmailConfirmRoute: ApiPublicEmailConfirmRoute,
  ApiPublicEmailWatchSubscribeRoute: ApiPublicEmailWatchSubscribeRoute,
  ApiPublicHooksAdminDailyDigestRoute: ApiPublicHooksAdminDailyDigestRoute,
  ApiPublicHooksKeepaBackfillCategoriesRoute:
    ApiPublicHooksKeepaBackfillCategoriesRoute,
  ApiPublicHooksKeepaRefreshRoute: ApiPublicHooksKeepaRefreshRoute,
  ApiPublicHooksKeepaSyncRoute: ApiPublicHooksKeepaSyncRoute,
  ApiPublicHooksPriceAlertCheckRoute: ApiPublicHooksPriceAlertCheckRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
